version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:5173" # external-port:internal-port
    volumes:
      - "/app/node_modules"
      - "./:/app"
